# -*- coding: utf-8 -*-
"""
Created for DDI Tox-Predict Project
Phase 1: Data Acquisition & Preprocessing (Final Step)

This script consolidates the disparate JSON results into a flattened Training Matrix.
It dynamically maps the actual Drug Names from Script 011 to their respective GroupIds,
extracts their SMILES from Script 007, and maps the Target Adverse Event rates.
"""

import json
import pandas as pd

def load_json(filepath):
    """Utility function to safely load JSON files."""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"Warning: File {filepath} not found.")
        return []

def main():
    print("Loading intermediate data files...")
    
    # 1. Load the distributions from Script 006
    distributions_data = load_json('trial_adverse_event_distributions_with_data_separated.json')
    
    # 2. Load the actual drug names assigned to each group from Script 011
    # Note: Ensure this matches the actual output filename from your 011 script
    drug_groups_data = load_json('gpt_filteres-special-trials-w-or-final.json')
    
    # 3. Load the extracted SMILES mapping from Script 007
    # Assuming format: [{"drug_name": "Tenofovir", "canonical_smiles": "CC(C)OC(=O)..."}, ...]
    smiles_mapping = load_json('drug_smiles_mapping.json') 
    
    # --- BUILD LOOKUP DICTIONARIES (O(1) Time Complexity) ---
    print("Building lookup dictionaries...")
    
    # Build SMILES dictionary
    smiles_dict = {}
    for item in smiles_mapping:
        if isinstance(item, dict) and 'drug_name' in item:
            smiles_dict[item['drug_name']] = item.get('canonical_smiles')

    # Build NCTId + GroupId -> Drugs Mapping
    group_drug_map = {}
    for trial in drug_groups_data:
        nct_id = trial.get('protocolSection', {}).get('identificationModule', {}).get('nctId')
        event_groups = trial.get('resultsSection', {}).get('adverseEventsModule', {}).get('eventGroups', [])
        
        for eg in event_groups:
            g_id = eg.get('id')
            drugs = eg.get('drugs', []) # This array was generated by GPT in Script 011
            if nct_id and g_id and drugs:
                # Key format: "NCT01234567_EG000"
                group_drug_map[f"{nct_id}_{g_id}"] = drugs

    # --- FLATTEN THE DATA ---
    print("Flattening hierarchical JSON into the Training Matrix...")
    flattened_records = []

    for trial in distributions_data:
        protocol_section = trial.get('protocolSection', {})
        nct_id = protocol_section.get('identificationModule', {}).get('nctId', 'Unknown')
        
        distributions = trial.get('adverseEventDistributions', {})
        serious_events = distributions.get('seriousEvents', {})
        
        for group_id, ae_categories in serious_events.items():
            # Lookup the actual drugs for this specific group
            lookup_key = f"{nct_id}_{group_id}"
            drugs_in_group = group_drug_map.get(lookup_key, [])
            
            # Setup features for up to 2 drugs to support DDI (Drug-Drug Interaction) pairs
            drug_1 = drugs_in_group[0] if len(drugs_in_group) > 0 else 'Unknown'
            drug_2 = drugs_in_group[1] if len(drugs_in_group) > 1 else None
            
            record = {
                'NCTId': nct_id,
                'GroupId': group_id,
                'Drug_1': drug_1,
                'Canonical_SMILES_1': smiles_dict.get(drug_1, None),
                'Drug_2': drug_2,
                'Canonical_SMILES_2': smiles_dict.get(drug_2, None) if drug_2 else None
            }
            
            # Unroll Target Variables (Adverse Event Categories percentage)
            for category, percentage in ae_categories.items():
                clean_category = str(category).replace(' ', '_').replace('/', '_')
                col_name = f"Target_AE_{clean_category}"
                record[col_name] = percentage
                
            flattened_records.append(record)

    # Convert to Pandas DataFrame
    df = pd.DataFrame(flattened_records)
    
    # Fill missing target variables with 0.0%
    target_cols = [col for col in df.columns if str(col).startswith('Target_AE_')]
    df[target_cols] = df[target_cols].fillna(0.0)

    print(f"Flattened matrix shape before export: {df.shape}")
    
    # Export to CSV
    output_filename = 'training_matrix_raw.csv'
    df.to_csv(output_filename, index=False)
    print(f"✅ Successfully exported Raw Training Matrix to {output_filename}")

if __name__ == "__main__":
    main()